
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'SET DRAW RAND MOV JMP IFE IFN IFR REG ADDR COMMA NEWLINE ID COMMENT\n        expression : SET REG COMMA ADDR NEWLINE\n    \n        expression : MOV REG COMMA REG NEWLINE\n    \n        expression : IFE REG COMMA ADDR NEWLINE \n    \n        expression : IFN REG COMMA ADDR NEWLINE\n    \n        expression : IFR REG COMMA REG NEWLINE\n    \n        expression : JMP ADDR NEWLINE\n    '
    
_lr_action_items = {'SET':([0,],[1,]),'ADDR':([3,14,18,19,],[10,20,23,24,]),'IFR':([0,],[2,]),'JMP':([0,],[3,]),'NEWLINE':([10,20,21,22,23,24,],[16,25,26,27,28,29,]),'MOV':([0,],[4,]),'IFE':([0,],[5,]),'COMMA':([8,9,11,12,13,],[14,15,17,18,19,]),'IFN':([0,],[6,]),'REG':([1,2,4,5,6,15,17,],[8,9,11,12,13,21,22,]),'$end':([7,16,25,26,27,28,29,],[0,-6,-1,-5,-2,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> SET REG COMMA ADDR NEWLINE','expression',5,'p_expression_set','parseasm.py',11),
  ('expression -> MOV REG COMMA REG NEWLINE','expression',5,'p_expression_mov','parseasm.py',17),
  ('expression -> IFE REG COMMA ADDR NEWLINE','expression',5,'p_expression_ife','parseasm.py',23),
  ('expression -> IFN REG COMMA ADDR NEWLINE','expression',5,'p_expression_ifn','parseasm.py',29),
  ('expression -> IFR REG COMMA REG NEWLINE','expression',5,'p_expression_ifr','parseasm.py',35),
  ('expression -> JMP ADDR NEWLINE','expression',3,'p_expression_jmp','parseasm.py',41),
]
